aws:
  secretsmanager:
    enabled: true

spring:
  config.import: aws-secretsmanager:catCraze/catApiKey;catCraze/twilio
  datasource.url: ##
  datasource.username: ##
  datasource.password: ##
  jpa.database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#  jpa.hibernate.ddl-auto: update
